package soft3appbanco;

import DAO.TransaccionDAO;
import DTO.TransaccionDTO;
import Factory.FactoryDao;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Gerardo
 */
public class TransaccionIntFrm extends javax.swing.JInternalFrame {

    /**
     * Creates new form TransaccionIntFrm
     */
    public TransaccionIntFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblNroCuenta = new javax.swing.JLabel();
        jCBoxCuenta = new javax.swing.JComboBox<>();
        jlblTransaccion = new javax.swing.JLabel();
        jCBoxTransaccion = new javax.swing.JComboBox<>();
        jlblMonto = new javax.swing.JLabel();
        jTxtMonto = new javax.swing.JTextField();
        jlblFecha = new javax.swing.JLabel();
        btnTransaccion = new javax.swing.JButton();
        jlblMotivoTransaccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxAreaMotivo = new javax.swing.JTextArea();
        jfTxtFecha = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lblNroCuenta.setText("Nro Cuenta :");

        jlblTransaccion.setText("Transaccion :");

        jlblMonto.setText("Monto");

        jlblFecha.setText("Fecha");

        btnTransaccion.setText("Realizar Transaccion");
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });

        jlblMotivoTransaccion.setText("Motivo De Transaccion");

        jtxAreaMotivo.setColumns(20);
        jtxAreaMotivo.setRows(5);
        jScrollPane2.setViewportView(jtxAreaMotivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNroCuenta)
                            .addComponent(jlblTransaccion)
                            .addComponent(jlblMonto)
                            .addComponent(jlblFecha)
                            .addComponent(jlblMotivoTransaccion))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jfTxtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtMonto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBoxCuenta, javax.swing.GroupLayout.Alignment.LEADING, 0, 169, Short.MAX_VALUE)
                                .addComponent(jCBoxTransaccion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnTransaccion)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNroCuenta)
                    .addComponent(jCBoxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTransaccion)
                    .addComponent(jCBoxTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblMonto)
                    .addComponent(jTxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblFecha)
                        .addGap(51, 51, 51)
                        .addComponent(jlblMotivoTransaccion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jfTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnTransaccion)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionActionPerformed
        // TODO add your handling code here:
        //System.out.println(cmbidcategoria.getSelectedItem().toString());
        try {
            System.out.println("asasd");
            TransaccionDAO objDao = FactoryDao.getFactoryInstance().getNewTransaccionDAO();
            TransaccionDTO obj = new TransaccionDTO();
            obj.setMonto(jTxtMonto.getText());
            obj.setFecha(jfTxtFecha.getText());
            obj.setMotivoTransaccion(jtxAreaMotivo.getText());
            obj.setCategoriaIDFK(1);
            obj.setCuentaIDFK(1);

            System.out.println("antes");
            objDao.insert(obj);
            System.out.println("despues");
            System.out.println(obj);

        } catch (Exception ex) {
            System.out.println("No Inserto NI MIERDA");
            //Logger.getLogger(TransaccionGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTransaccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JComboBox<String> jCBoxCuenta;
    private javax.swing.JComboBox<String> jCBoxTransaccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtMonto;
    private javax.swing.JFormattedTextField jfTxtFecha;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblMonto;
    private javax.swing.JLabel jlblMotivoTransaccion;
    private javax.swing.JLabel jlblTransaccion;
    private javax.swing.JTextArea jtxAreaMotivo;
    private javax.swing.JLabel lblNroCuenta;
    // End of variables declaration//GEN-END:variables

}
