package soft3appbanco;

import DAO.TransaccionDao;
import DTO.TBLCategoriaTransaccionDTO;
import factory.FactoryDao;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Alvaro
 */
public class TranferenciaIntFrm extends javax.swing.JInternalFrame {

    /**
     * Creates new form TransaccionIntFrm
     */
    public TranferenciaIntFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jCBoxTransaccion = new javax.swing.JComboBox<String>();
        jlblMonto = new javax.swing.JLabel();
        jTxtMonto = new javax.swing.JTextField();
        lblNroCuenta = new javax.swing.JLabel();
        jCBoxCuenta = new javax.swing.JComboBox<String>();
        jlblTransaccion = new javax.swing.JLabel();
        jlblFecha = new javax.swing.JLabel();
        JDateFecha = new com.toedter.calendar.JDateChooser();
        btnTransaccion = new javax.swing.JButton();
        jlblMotivoTransaccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxAreaMotivo = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBoxTransaccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCBoxTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, -1));

        jlblMonto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblMonto.setText("Monto");
        jPanel1.add(jlblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));
        jPanel1.add(jTxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 64, 56, -1));

        lblNroCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNroCuenta.setText("Nro Cuenta :");
        jPanel1.add(lblNroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 22, -1, -1));

        jCBoxCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBoxCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(jCBoxCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, -1));

        jlblTransaccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTransaccion.setText("Tranferencia");
        jPanel1.add(jlblTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jlblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblFecha.setText("Fecha");
        jPanel1.add(jlblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 117, -1, -1));
        jPanel1.add(JDateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 149, 169, -1));

        btnTransaccion.setText("TRansferencia");
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 310, -1, 35));

        jlblMotivoTransaccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblMotivoTransaccion.setText("Motivo De Transaccion");
        jPanel1.add(jlblMotivoTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 184, -1, -1));

        jtxAreaMotivo.setColumns(20);
        jtxAreaMotivo.setRows(5);
        jScrollPane2.setViewportView(jtxAreaMotivo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 216, 248, 76));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTransaccionActionPerformed

    private void jCBoxCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateFecha;
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JComboBox<String> jCBoxCuenta;
    private javax.swing.JComboBox<String> jCBoxTransaccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtMonto;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblMonto;
    private javax.swing.JLabel jlblMotivoTransaccion;
    private javax.swing.JLabel jlblTransaccion;
    private javax.swing.JTextArea jtxAreaMotivo;
    private javax.swing.JLabel lblNroCuenta;
    // End of variables declaration//GEN-END:variables

}
